apiVersion: v1
kind: Service
metadata:
  name: django-chat-service
  labels:
    app: django-chat
spec:
  type: NodePort
  selector:
    app: django-chat
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000

